import React from "react";
import { nanoid } from 'nanoid'
import { getDatabase, child, red, set, get } from 'firebase/database'
import {isWebUrl} from 'valid-url'
import OverlayTrigger from 'react-bootstrap/OverlayTrigger'
import ToolTip from 'react-bootstrap/Tooltip'

function Form() {
    const [formData, setFormData] = useState({
        longURL:'', //Inputted long url from the user
        preferedAlias:'', //Optional user input
        generatedURL:'', //Uses either the optional input or a random short url generated by the app
        loading:false, //Shows spinng logo
        errors:[], //Keeps track of which fields on our form have errors
        errorMessage:{}, //Keeps track of the corresponding message for each error
        toolTipMessage:'Copy to Clip Board' //Will be updated as the user copies short url
    })

    //When the user clicks the submit button
    const onSubmit = async (event) => {
        event.preventDefault(); //Prevents the page from reloading.
    }

    return(
        <>

        </>
    )
}

export default Form